### PR TITLE
Fix memory leaks, add MultiString type

### PR DESCRIPTION
**Pull request by MikaelSmith**
**Cleanup memory usage by using shared_ptr**
Fix memory leaks by using std::shared_ptr. Leaks found using valgrind.

**Implement MultiString type**
Adds a MultiString type that reads arguments until the next flag or known subcommand, and provides them as a vector of strings.

**Prepare for 0.13.0 release**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This is potentially ready to go. I'd like to explore using undefined functions that are defined by specific template instances for making Horsewhisperer types extensible, but that's not necessary for PCP-405.

**Comment by MikaelSmith** [comment]
Oh, this should really have new tests.

**Comment by MikaelSmith** [comment]
Planning to add more tests around making sure MultiString doesn't interfere with actions.

**Comment by parisiale** [comment]
I found a typo in https://github.com/puppetlabs/horsewhisperer/blob/master/test/README.md, line 16. It would be nice to correct it for 0.13.0.

**Comment by parisiale** [comment]
The hardcoded version must be updated: https://github.com/puppetlabs/horsewhisperer/blob/master/include/horsewhisperer/horsewhisperer.h#L56.

**Comment by parisiale** [comment]
I suspect that this breaks the parsing of multiple action options as well as chained actions.
By running https://gist.github.com/parisiale/6fd84063649b50b96690c449d8322de3, I get unexpected behaviour:
```
10129 201018 ~code/horsewhisperer/examples (hw-mem●●) ❯ ./example gallop --destinations uno due --tired
Galloping into the night!
  Reaching uno
  Reaching due
10130 201018 ~code/horsewhisperer/examples (hw-mem●●) ❯ ./example gallop --destinations uno due trot mode_a mode_b
Unknown action: mode_a
Failed to parse the command line input.
```

**Comment by MikaelSmith** [comment]
Given that Horsewhisperer allows flags to be interspersed with action arguments, this may be a dead-end. The parsing would have to be more complicated to ensure the action arity is met while still accepting multiple options on a flag.

**Comment by MikaelSmith** [comment]
Ok, updated this so it should work. Added tests. Also added a note in the README with caveats around using it: can't accept arguments starting with dashes, and is finicky when used with actions with arguments. Neither apply to its usage in pxp-agent.

**Comment by parisiale** [comment]
The caveats are a very reasonable price to pay for having such new feature.
Tested the old behaviour with a CL tool that supports chained actions; no regressions.
The modified example (see above) works fine now.
👍

**Pull request merged**
